# Image Version
substitutions:
  _IMAGE_VERSION_56: '1.5.0'
  _IMAGE_VERSION_70: '1.5.0'
#  _IMAGE_VERSION_71: '1.5.0'
#  _IMAGE_VERSION_72: '1.5.0'
#  _IMAGE_VERSION_73: '1.4.0'
  _IMAGE_VERSION_74: '1.6.1'

# Cloud Build
steps:

  - id: "Decrypt Password"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      - "kms"
      - "decrypt"
      - "--ciphertext-file=./credentials/secrets.enc"
      - "--plaintext-file=./credentials/secrets.env"
      - "--location=global"
      - "--keyring=Resolutte"
      - "--key=docker-hub"

  - id: "Login to provide credentials for the push"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: 'bash'
    args: ['-c','cat ./credentials/secrets.env | docker login --username resolutte --password-stdin']

  - id: "Build the image php-fpm-5.6"
    name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '--build-arg'
    - 'version=${_IMAGE_VERSION_56}'
    - '-t'
    - 'resolutte/php-fpm-5.6:latest'
    - '-t'
    - 'resolutte/php-fpm-5.6:${_IMAGE_VERSION_56}'
    - '-f'
    - 'php-fpm-5.6/Dockerfile'
    - '.'

  - id: "Build the image php-fpm-7.0"
    name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '--build-arg'
    - 'version=${_IMAGE_VERSION_70}'
    - '-t'
    - 'resolutte/php-fpm-7.0:latest'
    - '-t'
    - 'resolutte/php-fpm-7.0:${_IMAGE_VERSION_70}'
    - '-f'
    - 'php-fpm-7.0/Dockerfile'
    - '.'

#  - id: "Build the image php-fpm-7.1"
#    name: 'gcr.io/cloud-builders/docker'
#    args:
#    - 'build'
#    - '--build-arg'
#    - 'version=${_IMAGE_VERSION_71}'
#    - '-t'
#    - 'resolutte/php-fpm-7.1:latest'
#    - '-t'
#    - 'resolutte/php-fpm-7.1:${_IMAGE_VERSION_71}'
#    - '-f'
#    - 'php-fpm-7.1/Dockerfile'
#    - '.'

#  - id: "Build the image php-fpm-7.2"
#    name: 'gcr.io/cloud-builders/docker'
#    args:
#    - 'build'
#    - '--build-arg'
#    - 'version=${_IMAGE_VERSION_72}'
#    - '-t'
#    - 'resolutte/php-fpm-7.2:latest'
#    - '-t'
#    - 'resolutte/php-fpm-7.2:${_IMAGE_VERSION_72}'
#    - '-f'
#    - 'php-fpm-7.2/Dockerfile'
#    - '.'

#  - id: "Build the image php-fpm-7.3"
#    name: 'gcr.io/cloud-builders/docker'
#    args:
#    - 'build'
#    - '--build-arg'
#    - 'version=${_IMAGE_VERSION_73}'
#    - '-t'
#    - 'resolutte/php-fpm-7.3:latest'
#    - '-t'
#    - 'resolutte/php-fpm-7.3:${_IMAGE_VERSION_73}'
#    - '-f'
#    - 'php-fpm-7.3/Dockerfile'
#    - '.'

  - id: "Build the image php-fpm-7.4"
    name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '--build-arg'
    - 'version=${_IMAGE_VERSION_74}'
    - '-t'
    - 'resolutte/php-fpm-7.4:latest'
    - '-t'
    - 'resolutte/php-fpm-7.4:${_IMAGE_VERSION_74}'
    - '-f'
    - 'php-fpm-7.4/Dockerfile'
    - '.'

# Push the image to Dockerhub.
images:
  - 'resolutte/php-fpm-5.6:latest'
  - 'resolutte/php-fpm-5.6:${_IMAGE_VERSION_56}'
  - 'resolutte/php-fpm-7.0:latest'
  - 'resolutte/php-fpm-7.0:${_IMAGE_VERSION_70}'
#  - 'resolutte/php-fpm-7.1:latest'
#  - 'resolutte/php-fpm-7.1:${_IMAGE_VERSION_71}'
#  - 'resolutte/php-fpm-7.2:latest'
#  - 'resolutte/php-fpm-7.2:${_IMAGE_VERSION_72}'
#  - 'resolutte/php-fpm-7.3:latest'
#  - 'resolutte/php-fpm-7.3:${_IMAGE_VERSION_73}'
  - 'resolutte/php-fpm-7.4:latest'
  - 'resolutte/php-fpm-7.4:${_IMAGE_VERSION_74}'