steps:

#- name: "gcr.io/cloud-builders/gcloud"
#  args:
#    - "kms"
#    - "decrypt"
#    - "--ciphertext-file=secrets.enc"
#    - "--plaintext-file=secrets.env"
#    - "--location=global"
#    - "--keyring=Resolutte"
#    - "--key=docker-hub"

## Login to provide credentials for the push.
#- name: "gcr.io/cloud-builders/docker"
#  entrypoint: 'bash'
#  args: ['-c','docker login --username resolutte --password-stdin < secrets.env']

# Login to provide credentials for the push.
- name: "gcr.io/cloud-builders/docker"
  entrypoint: 'bash'
  args: ['-c','echo $$PASSWORD','docker login --username=resolutte --password-stdin']
  secretEnv: ["PASSWORD"]

# Build the image.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg'
  - 'version=$SHORT_SHA'
  - '-t'
  - 'resolutte/php-fpm-5.6:latest'
  - '-t'
  - 'resolutte/php-fpm-5.6:1.0.0'
  - '-f'
  - 'php-fpm-5.6/Dockerfile'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','resolutte/php-fpm-5.6:latest']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','resolutte/php-fpm-5.6:1.0.0']

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg'
  - 'version=$SHORT_SHA'
  - '-t'
  - 'resolutte/php-fpm-7.2:latest'
  - '-t'
  - 'resolutte/php-fpm-7.2:1.0.0'
  - '-f'
  - 'php-fpm-7.2/Dockerfile'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg'
  - 'version=$SHORT_SHA'
  - '-t'
  - 'resolutte/php-fpm-7.3:latest'
  - '-t'
  - 'resolutte/php-fpm-7.3:1.0.0'
  - '-f'
  - 'php-fpm-7.3/Dockerfile'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg'
  - 'version=$SHORT_SHA'
  - '-t'
  - 'resolutte/php-fpm-7.4:latest'
  - '-t'
  - 'resolutte/php-fpm-7.4:1.0.0'
  - '-f'
  - 'php-fpm-7.4/Dockerfile'
  - '.'

# Push the image to Dockerhub.
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','resolutte/php-fpm-5.6:latest']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','resolutte/php-fpm-5.6:1.0.0']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','resolutte/php-fpm-7.2:latest']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','resolutte/php-fpm-7.2:1.0.0']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','resolutte/php-fpm-7.3:latest']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','resolutte/php-fpm-7.3:1.0.0']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','resolutte/php-fpm-7.4:latest']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','resolutte/php-fpm-7.4:1.0.0']

# Dockerhub Password
secrets:
  - kmsKeyName: 'projects/resolutte-264622/locations/global/keyRings/Resolutte/cryptoKeys/docker-hub'
    secretEnv:
      PASSWORD: 'CiQAdXh3aOtPQ89eGQzHVg83jJ7r9Zi349FMIE85FJ+gQgjGWBYSPQDhENgDQv4NrThQMDWFP9VKteKvmqMiIDHzqvAqxvLBtoOhnPrGbU94Ka3hYKEuAxn+cKZOM5kL1TFM2Ko='