steps:

  - id: "Decrypt Password"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      - "kms"
      - "decrypt"
      - "--ciphertext-file=secrets.enc"
      - "--plaintext-file=secrets.env"
      - "--location=global"
      - "--keyring=Resolutte"
      - "--key=docker-hub"

  - id: "Login to provide credentials for the push"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: 'bash'
    args: ['-c','cat secrets.env | docker login --username resolutte --password-stdin']

  - id: "Build the image php-fpm-5.6"
    name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '--build-arg'
    - 'version=${_IMAGE_VERSION_1}'
    - '-t'
    - 'resolutte/php-fpm-5.6:latest'
    - '-t'
    - 'resolutte/php-fpm-5.6:${_IMAGE_VERSION_1}'
    - '-f'
    - 'php-fpm-5.6/Dockerfile'
    - '.'

  - id: "Build the image php-fpm-7.0"
    name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '--build-arg'
    - 'version=${_IMAGE_VERSION_1}'
    - '-t'
    - 'resolutte/php-fpm-7.0:latest'
    - '-t'
    - 'resolutte/php-fpm-7.0:${_IMAGE_VERSION_1}'
    - '-f'
    - 'php-fpm-7.0/Dockerfile'
    - '.'

  - id: "Build the image php-fpm-7.1"
    name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '--build-arg'
    - 'version=${_IMAGE_VERSION_1}'
    - '-t'
    - 'resolutte/php-fpm-7.1:latest'
    - '-t'
    - 'resolutte/php-fpm-7.1:${_IMAGE_VERSION_1}'
    - '-f'
    - 'php-fpm-7.1/Dockerfile'
    - '.'

  - id: "Build the image php-fpm-7.2"
    name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '--build-arg'
    - 'version=${_IMAGE_VERSION_1}'
    - '-t'
    - 'resolutte/php-fpm-7.2:latest'
    - '-t'
    - 'resolutte/php-fpm-7.2:${_IMAGE_VERSION_1}'
    - '-f'
    - 'php-fpm-7.2/Dockerfile'
    - '.'

  - id: "Build the image php-fpm-7.3"
    name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '--build-arg'
    - 'version=${_IMAGE_VERSION_1}'
    - '-t'
    - 'resolutte/php-fpm-7.3:latest'
    - '-t'
    - 'resolutte/php-fpm-7.3:${_IMAGE_VERSION_1}'
    - '-f'
    - 'php-fpm-7.3/Dockerfile'
    - '.'

  - id: "Build the image php-fpm-7.4"
    name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '--build-arg'
    - 'version=${_IMAGE_VERSION_1}'
    - '-t'
    - 'resolutte/php-fpm-7.4:latest'
    - '-t'
    - 'resolutte/php-fpm-7.4:${_IMAGE_VERSION_1}'
    - '-f'
    - 'php-fpm-7.4/Dockerfile'
    - '.'

# Image Version
substitutions:
  _IMAGE_VERSION_1: '1.5.0'

# Push the image to Dockerhub.
images:
  - 'resolutte/php-fpm-5.6:latest'
  - 'resolutte/php-fpm-5.6:${_IMAGE_VERSION_1}'
  - 'resolutte/php-fpm-7.0:latest'
  - 'resolutte/php-fpm-7.0:${_IMAGE_VERSION_1}'
  - 'resolutte/php-fpm-7.1:latest'
  - 'resolutte/php-fpm-7.1:${_IMAGE_VERSION_1}'
  - 'resolutte/php-fpm-7.2:latest'
  - 'resolutte/php-fpm-7.2:${_IMAGE_VERSION_1}'
  - 'resolutte/php-fpm-7.3:latest'
  - 'resolutte/php-fpm-7.3:${_IMAGE_VERSION_1}'
  - 'resolutte/php-fpm-7.4:latest'
  - 'resolutte/php-fpm-7.4:${_IMAGE_VERSION_1}'