steps:

- id: "Building image from Dockerfile PHP 5.6"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/php-fpm-5.6:latest','-f','php-fpm-5.6/Dockerfile','.']

- id: "Pushing image PHP 5.6"
  name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/$PROJECT_ID/php-fpm-5.6:latest']


- id: "Building image from Dockerfile PHP 7.2"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/php-fpm-7.2:latest','-f','php-fpm-7.2/Dockerfile','.']

- id: "Pushing image PHP 7.2"
  name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/$PROJECT_ID/php-fpm-7.2:latest']


- id: "Building image from Dockerfile PHP 7.3"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/php-fpm-7.3:latest','-f','php-fpm-7.2/Dockerfile','.']

- id: "Pushing image PHP 7.3"
  name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/$PROJECT_ID/php-fpm-7.3:latest']


- id: "Building image from Dockerfile PHP 7.4"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/php-fpm-7.4:latest','-f','php-fpm-7.2/Dockerfile','.']

- id: "Pushing image PHP 7.4"
  name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/$PROJECT_ID/php-fpm-7.4:latest']


- id: "Building image from Dockerfile HPA"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/php-apache-hpa:latest','-f','php-apache-hpa/Dockerfile','.']

- id: "Pushing image HPA"
  name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/$PROJECT_ID/php-apache-hpa:latest']